apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: webapi-central-ct3
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: webapi-central-ct3
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: webapi-central-ct3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: webapi-central-ct3
  namespace: default
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: cluster-identity
  location: centralus
  resourceGroupName: webapps-clusters-rg
  sshPublicKey: ""
  subscriptionID: 16370fca-8e3f-4920-9c3b-ca98f1791ac1
  version: 1.25.5
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: webapi-central-ct3
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: webapi-central-ct3-pool0
  namespace: default
spec:
  clusterName: webapi-central-ct3
  replicas: 3
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: webapi-central-ct3
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: webapi-central-ct3-pool0
      version: 1.25.5
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: webapi-central-ct3-pool0
  namespace: default
spec:
  mode: System
  name: pool0
  sku: Standard_D2s_v3
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: webapi-central-ct3-pool1
  namespace: default
spec:
  clusterName: webapi-central-ct3
  replicas: 3
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: webapi-central-ct3
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: webapi-central-ct3-pool1
      version: 1.25.5
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: webapi-central-ct3-pool1
  namespace: default
spec:
  mode: User
  name: pool1
  sku: Standard_D2s_v3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: 19c4548f-0244-46ea-bfd4-516081aaa265
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: 992fa5ac-98be-45a4-ac77-2d773df392c2
  type: ServicePrincipal
