apiVersion: fleet.azure.com/v1alpha1
kind: ClusterResourcePlacement
metadata:
  name: carvana-demo
spec:
  resourceSelectors:
    - group: ""
      version: v1
      kind: Namespace
      name: good-fellas-demo
  policy:
    affinity:
      clusterAffinity:
        clusterSelectorTerms:
          - labelSelector:
              matchLabels:
                workload: serverless
